apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agentic-cloud
  namespace: agentic-cloud
  labels:
    app.kubernetes.io/name: agentic-cloud
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agentic-cloud
