apiVersion: v1
kind: Secret
metadata:
  name: agentic-cloud-secrets
  namespace: agentic-cloud
  labels:
    app.kubernetes.io/name: agentic-cloud
type: Opaque
stringData:
  # AWS SES Configuration for Waitlist Emails
  AWS_SES_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SES_SECRET_ACCESS_KEY: "CHANGE_ME"
  AWS_SES_REGION: "us-east-1"
  AWS_SES_FROM_EMAIL: "noreply@callsphere.tech"
